# Generated by Django 5.2.4 on 2025-07-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_theme"),
        ("users", "0006_subscription"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
