# Generated by Django 5.2.4 on 2025-07-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
