# Generated by Django 5.2.4 on 2025-08-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_lesson_price"),
        ("users", "0008_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="course_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_course_price",
                to="materials.course",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_lesson_price",
                to="materials.lesson",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="URL платежной сессии"),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID платежной сессии"),
        ),
    ]
