services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_PASSWORD: "11111"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker

  celery:
    image: celery:latest
    command: celery -A config.celery worker --loglevel=info
    depends_on:
      - web
    env_file:
      - .env.docker

  celery-beat:
    image: celery:latest
    command: celery -A config.celery beat --loglevel=info
    depends_on:
      - celery
    env_file:
      - .env.docker

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  celerybeat:
