# Generated by Django 5.2.4 on 2025-07-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_remove_lesson_theme_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="materials.course",
                verbose_name="Из курса",
            ),
        ),
    ]
