# Generated by Django 5.2.4 on 2025-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена курса"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена урока"),
            preserve_default=False,
        ),
    ]
