# Generated by Django 5.2.5 on 2025-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
