# Generated by Django 5.2.5 on 2025-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_lesson_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
