# Generated by Django 5.2.5 on 2025-08-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_course_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена урока"
            ),
        ),
    ]
